crm/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # Startseite-URL-------------------------------------------------------------
    path('', views.dashboard, name='crm_dashboard'),
    # Kunden-URLs-------------------------------------------------------------
    path('kundenliste/', views.kundenliste, name='kundenliste'),
    path("kunde_anlegen/", views.KundeAnlegen, name='kunde_anlegen'),
    path("kunde_loeschen/<str:pk>/", views.KundeLoeschen, name='kunde_loeschen'),
    path('pdf_view_kundenliste/', views.ViewKundenListePDF.as_view(), name="pdf_view_kundenliste"),
    path('pdf_download_kundenliste/', views.DownloadKundenlistePDF.as_view(), name="pdf_download_kundenliste"),
    path("kunde_aktualisieren/<str:pk>/", views.KundeAktualisieren, name='kunde_aktualisieren'),
    path('csv_download_kundenliste/', views.csv_download_kundenliste, name="csv_download_kundenliste"),
    # Mitarbeiter-URLs-------------------------------------------------------------
    path('mitarbeiterliste/', views.mitarbeiterliste, name='mitarbeiterliste'),
    path("mitarbeiter_anlegen/", views.mitarbeiterAnlegen, name='mitarbeiter_anlegen'),
    path("mitarbeiter_loeschen/<str:pk>/", views.mitarbeiterLoeschen, name='mitarbeiter_loeschen'),
    path("mitarbeiter_aktualisieren/<str:pk>/", views.mitarbeiterAktualisieren, name='mitarbeiter_aktualisieren'),
    # Auftrags-URLs-------------------------------------------------------------
    path("auftragsliste/", views.auftragsliste, name="auftragsliste"),
    path("auftrag_anlegen", views.auftragAnlegen, name="auftrag_anlegen"),
    path("auftrag_aktualisieren/<str:pk>/", views.auftragAktualisieren, name='auftrag_aktualisieren'),
    path("auftrag_loeschen/<str:pk>/", views.auftragLoeschen, name='auftrag_loeschen'),
    path('pdf_download/auftragsliste/', views.DownloadAuftragslistePDF.as_view(), name="auftragsliste_pdf_download"),
    path('csv_download/auftragsliste/', views.csv_download_auftragsliste, name="csv_auftragsliste_download"),
    # Rechnungs-URLs-------------------------------------------------------------
    path("rechnungsliste/", views.rechnungsliste, name="rechnungsliste"),
    path("rechnung_anlegen", views.rechnungAnlegen, name="rechnung_anlegen"),
    path("rechnung_aktualisieren/<str:pk>/", views.rechnungAktualisieren, name='rechnung_aktualisieren'),
    path("rechnung_loeschen/<str:pk>/", views.rechnungLoeschen, name='rechnung_loeschen'),
    path('pdf_view/<str:pk>', views.ViewPDF.as_view(), name="pdf_view"),
    path('pdf_download/<str:pk>', views.DownloadPDF.as_view(), name="pdf_download"),
    path('csv_download/<str:pk>', views.csv_download, name="csv_download"),
    # Login-URLs-------------------------------------------------------------
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    # Passwort zurücksetzen URLs
    path('passwort_zuruecksetzen/', auth_views.PasswordResetView.as_view(template_name='crm/passwort_zuruecksetzen.html'), name='reset_password'),
    path('passwort_zuruecksetzen/email_gesendet/', auth_views.PasswordResetDoneView.as_view(template_name='crm/passwort_zuruecksetzen_email.html'), name='password_reset_done'),
    path('passwort_zuruecksetzen/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='crm/passwort_zuruecksetzen_formular.html'), name='password_reset_confirm'),
    path('passwort_erfolgreich_zuruecksetzen/', auth_views.PasswordResetCompleteView.as_view(template_name='crm/passwort_erfolgreich_zurueckgesetzt.html'), name='password_reset_complete'),
]

happyqr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('menucard/', include('menucard.urls')),
]

menucard/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.dashboard, name='menucard_dashboard'),

    path('profil/', views.profil_bearbeiten, name="profil"),

    # Vorspeisen URLs
    path('vorspeisen/', views.vorspeisen, name='vorspeisen'),
    path('vorspeisen-add/', views.vorspeisen_anlegen, name='vorspeisen_anlegen'),
    path('vorspeisen-bearbeiten/<str:pk>/', views.vorspeisen_bearbeiten, name='vorspeisen_bearbeiten'),
    path('vorspeisen-loeschen/<str:pk>/', views.vorspeisen_loeschen, name='vorspeisen_loeschen'),

    # Hauptspeisen URLs
    path('hauptspeisen/', views.hauptspeisen, name='hauptspeisen'),
    path('hauptspeisen-add/', views.hauptspeisen_anlegen, name='hauptspeisen_anlegen'),
    path('hauptspeisen-bearbeiten/<str:pk>/', views.hauptspeisen_bearbeiten, name='hauptspeisen_bearbeiten'),
    path('hauptspeisen-loeschen/<str:pk>/', views.hauptspeise_loeschen, name='hauptspeise_loeschen'),

    # Nachspeisen URLs
    path('nachspeisen/', views.nachspeisen, name='nachspeisen'),
    path('nachspeisen-add/', views.nachspeisen_anlegen, name='nachspeisen_anlegen'),
    path('nachspeisen-bearbeiten/<str:pk>/', views.nachspeisen_bearbeiten, name='nachspeisen_bearbeiten'),
    path('nachspeisen-loeschen/<str:pk>/', views.nachspeisen_loeschen, name='nachspeisen_loeschen'),

    # Alkoholhaltige Drinks URLs
    path('alkoholhaltigedrinks/', views.alkoholhaltigedrinks, name='alkoholhaltigedrinks'),
    path('alkoholhaltigedrinks-add/', views.alkoholhaltigedrinks_anlegen, name='alkoholhaltigedrinks_anlegen'),
    path('alkoholhaltigedrinks-bearbeiten/<str:pk>/', views.alkoholhaltigedrinks_bearbeiten,
         name='alkoholhaltigedrinks_bearbeiten'),
    path('alkoholhaltigedrinks-loeschen/<str:pk>/', views.alkoholhaltigedrinks_loeschen,
         name='alkoholhaltigedrinks_loeschen'),

    # Alkoholfreie Drinks URLs
    path('alkoholfreiedrinks/', views.alkfreiedrinks, name='alkfreiedrinks'),
    path('alkoholfreiedrinks-add/', views.alkfreiedrinks_anlegen, name='alkfreiedrinks_anlegen'),
    path('alkoholfreiedrinks-bearbeiten/<str:pk>/', views.alkfreiedrinks_bearbeiten, name='alkfreiedrinks_bearbeiten'),
    path('alkoholfreiedrinks-loeschen/<str:pk>/', views.alkfreiedrinks_loeschen, name='alkfreiedrinks_loeschen'),

    # Snacks URLs
    path('snacks/', views.snacks, name='snacks'),
    path('snacks-add/', views.snacks_anlegen, name='snacks_anlegen'),
    path('snacks-bearbeiten/<str:pk>/', views.snacks_bearbeiten, name='snacks_bearbeiten'),
    path('snacks-loeschen/<str:pk>/', views.snacks_loeschen, name='snacks_loeschen'),

    # Menucard URL
    path(r'menucard_view/<str:username>', views.menucard, name='menucard'),
    path('logout/', views.logout_view, name='logout'),

    # covidform URLs
    path(r'menucard_view/covidform/<str:username>', views.besucher_anlegen, name='covidform'),
    path('besucher_daten/', views.besucher_daten, name='besucherdaten'),
    path('besucher_loeschen/<str:pk>/', views.besucher_loeschen, name='besucher_loeschen'),
    # covidform export urls
    path('besucherliste_pdf_view/', views.ViewBesucherListePDF.as_view(), name="besucherliste_pdf_view"),
    path('besucherliste_pdf_download/', views.DownloadBesucherlistePDF.as_view(), name="besucherliste_pdf_download"),
    path('besucherliste_csv_download/', views.csv_download_besucherliste, name="besucherliste_csv_download"),

    #QR Code url
    path("qr/", views.test_qr, name="test_qr"),

    # Datenschutz
    path('datenschutzerklaerung/', views.datenschutz, name='datenschutz'),

    # Handbuch
    path('happy-qr/handbuch/', views.kunden_handbuch, name='kunden_handbuch'),

    #Rechnung URL
    path('pdf_download/', views.DownloadPDF_Rechnung.as_view(), name="pdf_download_rechnung"),
]

crm/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User


# Create your models here.

class Mitarbeiter(models.Model):
    """
        Eine Klasse zur Repräsentation eines Mitarbeiters

        ...

        Attributes
        ----------
        vorname : charfield
            Vorname des Mitarbeiters
        nachname : decimalfield
            Nachname des Mitarbeiters
        email : emailfield
            Email-Adresse des Mitarbeiters
        telefon : phonenumberfield
            Telefonnummer des Mitarbeiters

        Methods
        -------
        __str__():
            Gibt den Vor- und Nachnamen des Mitarbeiters aus
        """
    vorname = models.CharField(max_length=45, null=False)
    nachname = models.CharField(max_length=45, null=False)
    email = models.EmailField()
    telefon = PhoneNumberField(null=True, blank=True)

    def __str__(self):
        return f'{self.vorname} {self.nachname}'


class Kunde(models.Model):
    """
        Eine Klasse zur Repräsentation eines Besuchers

        ...

        Attributes
        ----------
        user : user
            Django-User des Kunden
        vorname : charfield
            Vorname des Kunden
        nachname : decimalfield
            Nachname des Kunden
        email : emailfield
            Email-Adresse des Kunden
        telefon : phonenumberfield
            Telefonnummer des Kunden
        web : charfield
            Website des Kunden
        notiz : textfield
            Notizen für den Kunden
        template : charfield
            Ausgewähltes Template des Kunden

        Methods
        -------
        __str__():
            Gibt den Vor- und Nachnamen des Kunden aus
        """
    TEMPLATE = [
        ('Template 1', 'Template 1'),
        ('Template 2', 'Template 2'),
        ('Template 3', 'Template 3')
    ]

    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    vorname = models.CharField(max_length=45, null=False)
    nachname = models.CharField(max_length=45, null=False)
    email = models.EmailField(null=True, blank=True)
    telefon = PhoneNumberField(null=True, blank=True)
    web = models.CharField(max_length=200, null=True, blank=True)
    notiz = models.TextField(null=True, blank=True)
    template = models.CharField(max_length=20, choices=TEMPLATE, default='Template 1')

    def __str__(self):
        return f'{self.vorname} {self.nachname}'


class Auftrag(models.Model):
    """
        Eine Klasse zur Repräsentation eines Auftrags

        ...

        Attributes
        ----------
        kunde : foreignkey
            Fremdschlüssel des Kunden
        produkt : charfield
            Enthaltenes Produkt des Auftrags
        status : charfield
            Status des Auftrags
        auftrag_vom : datetimefield
            Datum der Erstellung des Auftrags
        telefon : phonenumberfield
            Telefonnummer des Kunden
        preis : decimalfield
            Preis des Auftrags
        notiz : textfield
            Notizen für den Auftrag

        Methods
        -------
        __str__():
            Gibt die Auftragsnummer und den Namen des Kunden aus
        """
    PRODUKT = [
        ('Digital Menucard', 'Digital Menucard')
    ]

    STATUS = [
        ('Eingegangen', 'Eingegangen'),
        ('In Bearbeitung', 'In Bearbeitung'),
        ('Abgeschlossen', 'Abgeschlossen')
    ]

    kunde = models.ForeignKey(Kunde, null=True, on_delete=models.SET_NULL)
    produkt = models.CharField(max_length=45, choices=PRODUKT, default='Digital Menucard')
    status = models.CharField(max_length=45, choices=STATUS, default='Eingegangen')
    auftrag_vom = models.DateTimeField(auto_now_add=True, null=True)
    preis = models.DecimalField(max_length=8, max_digits=8, decimal_places=2, default='')
    notiz = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Auftragsnummer: {self.id}, Kunde {self.kunde}'


class Rechnung(models.Model):
    """
        Eine Klasse zur Repräsentation eines Auftrags

        ...

        Attributes
        ----------
        kunde : foreignkey
            Fremdschlüssel des Kunden
        auftrag : foreignkey
            Fremdschlüssel des Auftrags
        datum : datefield
            Datum der Erstellung der Rechnung

        Methods
        -------
        __str__():
            Gibt die Rechnungsnummer und den Vor- und Nachnamen des Kunden aus
        """
    kunde = models.ForeignKey(Kunde, null=True, on_delete=models.SET_NULL)
    auftrag = models.ForeignKey(Auftrag, null=True, on_delete=models.SET_NULL)
    datum = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Rechnungsnummer: {self.id}, Kunde: {self.kunde}'

menucard/templates/menucard/Profil.html
{% extends 'menucard/base.html' %}
{% load crispy_forms_filters %}

{% block body %}
<div class="row mt-3">
    <div class="col">
        <h2>Profil bearbeiten</h2>
        <hr>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        {% for msg in messages %}
        <div class="alert alert-success" role="alert">
            {{msg}}
        </div>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            {{form | crispy}}
            <button class="btn btn-success" type="submit">Speichern</button>
            <a href="{% url 'menucard_dashboard'%}" class="btn btn-danger">Abbrechen</a>
        </form>
        <br>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#staticBackdrop">
            Passwort ändern
        </button>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
             aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Passwort ändern</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <form method="POST">
                            {% csrf_token %}
                            {{ pwform | crispy }}
                            <button type="submit" class="btn btn-success">Speichern</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Abbrechen</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

menucard/templates/menucard/alkfreiedrinks_loeschen.html
{% extends 'menucard/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

    <div class="row mt-3">
        <div class="col">
            <h2>Getränk löschen</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col mt-3">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="alert alert-danger" role="alert">
                        <span class="fas fa-exclamation-triangle"></span>
                        Möchten Sie das folgende Getränk wirklich löschen?
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Getränk</strong><br> {{ softdrink.name }}</li>
                        <li class="list-group-item">
                            <strong>Beschreibung</strong><br>
                            {% if softdrink.beschreibung == '' %}
                                (Leer)
                            {% else %}
                                {{ softdrink.beschreibung }}
                            {% endif %}
                        </li>
                        <li class="list-group-item"><strong>Preis</strong><br>{{ softdrink.preis }} EUR</li>
                    </ul>
                    <br>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            <span class="fas fa-trash"></span> Löschen
                        </button>
                        <a href="{% url 'alkfreiedrinks' %}" class="btn btn-secondary">
                            <span class="fas fa-times-circle"></span> Abbrechen
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

menucard/templates/menucard/alkoholhaltigedrinks.html
{% extends 'menucard/base.html' %}

{% block body %}

    <!-- HEADER -->
    <div class="row mt-3">
        <div class="col">
            <h2>Alkoholhaltige Getränke</h2>
            <hr>
        </div>
    </div>

    <!-- BUTTON GROUP    -->
    <div class="row mt-3">
        <div class="col">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'menucard_dashboard' %}" class="btn btn-outline-primary">
                    <span class="fas fa-angle-left"></span> Zurück zum Dashboard
                </a>
                <a href="{% url 'alkoholhaltigedrinks_anlegen' %}" class="btn btn-outline-primary">
                    <span class="fas fa-plus"></span> Getränk hinzufügen
                </a>
            </div>
        </div>
    </div>

    <!-- TABLE -->
    <div class="row mt-3">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-sm table-hover table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">Getränk</th>
                        <th scope="col">Centiliter</th>
                        <th scope="col">Beschreibung</th>
                        <th scope="col">Zusatzstoffe</th>
                        <th scope="col" class="text-right">Preis</th>
                        <th scope="col" class="text-center">
                            <span class="fas fa-edit"></span>
                        </th>
                        <th scope="col" class="text-center">
                            <span class="fas fa-trash"></span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in alkdrink %}
                        <tr>
                            <td>{{ i.name }}</td>
                            <td>{{ i.centiliter }}</td>
                            <td>{{ i.beschreibung }}</td>
                            <td>{{ i.zusatzstoffe }}</td>
                            <td class="text-right">{{ i.preis }} EUR</td>
                            <td data-toggle="tooltip" data-placement="top" title="Alkoholhaltige Drink bearbeiten"
                                class="text-center">
                                <a href="{% url 'alkoholhaltigedrinks_bearbeiten' i.id %}">
                                    <span class="fas fa-edit"></span>
                                </a>
                            </td>
                            <td data-toggle="tooltip" data-placement="top" title="Alkoholhaltige Drinks löschen"
                                class="text-center">
                                <a href="{% url 'alkoholhaltigedrinks_loeschen' i.id %}">
                                    <span class="fas fa-trash" style="color: crimson"></span>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

menucard/templates/menucard/dashboard.html
{% extends 'menucard/base.html' %}
{% load crispy_forms_filters %}

{% block body %}
    <div class="row mt-3">
        <div class="col">
            <h2>Dashboard</h2>
            <hr>
        </div>
    </div>

    {% if auftrag %}
        {% if auftrag.status == 'Eingegangen' %}
            <div class="card">
                <div class="card-body">
                    <p>Ihr Auftrag ist <strong>{{ auftrag.status }}</strong></p>
                </div>
            </div>
        {% elif auftrag.status == 'In Bearbeitung' %}
            <div class="card">
                <div class="card-body">
                    <p>Ihr Auftrag ist <strong>{{ auftrag.status }}</strong></p>
                </div>
            </div>
        {% else %}
            <!-- KARTE -->
            <div class="row">
                <div class="col">
                    <!-- BUTTON GROUP -->
                    <div class="btn-group" role="group" aria-label="Buttons">
                        <a class="btn btn-outline-primary" href="{% url 'menucard' request.user.username %}"
                           target="_blank">
                            <span class="fas fa-external-link-alt"></span> Zur Menükarte
                        </a>

                        <a class="btn btn-outline-primary" href="{% url 'test_qr' %}">
                            <span class="fas fa-qrcode"></span> QR-Code generieren
                        </a>
                        {% if kunde.rechnung_set.count > 0 %}
                                   <a class="btn btn-outline-primary" href="{% url 'pdf_download_rechnung' %}">
                            <span class="fas fa-file"></span> Rechnung herunterladen
                                   </a>
                        {% else %}

                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col">
                    {% for msg in messages %}
                        {% if form.is_valid %}
                            <div class="alert alert-success" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <span class="fas fa-check-circle"></span> {{ msg }}
                            </div>
                        {% else %}
                            <div class="alert alert-danger" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <span class="fas fa-exclamation-triangle"></span> {{ msg }}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="card-deck mb-4">
                        <!-- VORSPEISEN -->
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">Vorspeisen</h5>
                                <p class="card-text">
                                    {% if count_vorspeisen > 1 or count_vorspeisen == 0 %}
                                        Sie haben {{ count_vorspeisen }} Vorspeisen angelegt.
                                    {% else %}
                                        Sie haben {{ count_vorspeisen }} Vorspeise angelegt.
                                    {% endif %}
                                </p>
                                <a href="{% url 'vorspeisen' %}" class="btn btn-outline-primary btn-sm">Anzeigen</a>
                            </div>
                        </div>

                        <!-- HAUPTSPEISEN -->
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">Hauptspeisen</h5>
                                <p class="card-text">
                                    {% if count_hauptspeisen > 1 or count_hauptspeisen == 0 %}
                                        Sie haben {{ count_hauptspeisen }} Hauptspeisen angelegt.
                                    {% else %}
                                        Sie haben {{ count_hauptspeisen }} Hauptspeise angelegt.
                                    {% endif %}
                                </p>
                                <a href="{% url 'hauptspeisen' %}"
                                   class="btn btn-outline-primary btn-sm">Anzeigen</a>
                            </div>
                        </div>

                        <!-- NACHSPEISEN -->
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">Nachspeisen</h5>
                                <p class="card-text">
                                    {% if count_nachspeisen > 1 or count_nachspeisen == 0  %}
                                        Sie haben {{ count_nachspeisen }} Nachspeisen angelegt.
                                    {% else %}
                                        Sie haben {{ count_nachspeisen }} Nachspeise angelegt.
                                    {% endif %}
                                </p>
                                <a href="{% url 'nachspeisen' %}"
                                   class="btn btn-outline-primary btn-sm">Anzeigen</a>
                            </div>
                        </div>

                    </div>
                    <div class="card-deck mb-4">
                        <!-- SNACKS -->
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">Snacks</h5>
                                <p class="card-text">
                                    {% if count_snacks > 1 or count_snacks == 0 %}
                                        Sie haben {{ count_snacks }} Snacks angelegt.
                                    {% else %}
                                        Sie haben {{ count_snacks }} Snack angelegt.
                                    {% endif %}
                                </p>
                                <a href="{% url 'snacks' %}" class="btn btn-outline-primary btn-sm">Anzeigen</a>
                            </div>
                        </div>

                        <!-- SOFTDRINKS -->
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">Alkoholfreie Getränke</h5>
                                <p class="card-text">
                                    {% if count_alkfreidrinks > 1 or count_alkfreidrinks == 0%}
                                        Sie haben {{ count_alkfreidrinks }} Softdrinks angelegt.
                                    {% else %}
                                        Sie haben {{ count_alkfreidrinks }} alkoholfreies Getränk angelegt.
                                    {% endif %}
                                </p>
                                <a href="{% url 'alkfreiedrinks' %}"
                                   class="btn btn-outline-primary btn-sm">Anzeigen</a>
                            </div>
                        </div>

                        <!-- ALKOHOLHALTIGE DRINKS -->
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">Alkoholhaltige Getränke</h5>
                                <p class="card-text">
                                    {% if count_alkdrinks > 1 or count_alkdrinks == 0 %}
                                        Sie haben {{ count_alkdrinks }} alkoholhaltige Getränke angelegt.
                                    {% else %}
                                        Sie haben {{ count_alkdrinks }} alkoholhaltiges Getränk angelegt.
                                    {% endif %}
                                </p>
                                <a href="{% url 'alkoholhaltigedrinks' %}"
                                   class="btn btn-outline-primary btn-sm">Anzeigen</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- TEMPLATE -->
            <div class="row mt-4">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-header">
                            Template-Auswahl
                        </div>
                        <div class="card-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button class="btn btn-primary" type="submit">Speichern</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% else %}
        <div class="row mt-3">
            <div class="col">
                <p>
                    Sie haben noch keine Aufträge erstellt. Bitte <a href="mailto:info@happyqr.de">kontaktieren</a> Sie
                    den Happy-QR Vertrieb.
                </p>

            </div>
        </div>

    {% endif %}




{% endblock body %}

menucard/templates/menucard/hauptspeise_loeschen.html
{% extends 'menucard/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

    <div class="row mt-3">
        <div class="col">
            <h2>Hauptspeise löschen</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col mt-3">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="alert alert-danger" role="alert">
                        <span class="fas fa-exclamation-triangle"></span>
                        Möchten Sie die folgende Hauptspeise wirklich löschen?
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Hauptspeise</strong><br> {{ hauptspeise.name }}</li>
                        <li class="list-group-item">
                         <strong>Beschreibung</strong><br>
                            {% if hauptspeise.beschreibung == '' %}
                                (Leer)
                            {% else %}
                                {{ hauptspeise.beschreibung }}
                            {% endif %}
                        </li>
                        <li class="list-group-item"> <strong>Preis</strong><br>{{ hauptspeise.preis }} EUR</li>
                    </ul>
                    <br>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">
                            <span class="fas fa-trash"></span> Löschen
                        </button>
                        <a href="{% url 'hauptspeise' %}" class="btn btn-secondary">
                            <span class="fas fa-times-circle"></span> Abbrechen
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}